// Battlegrounds-style tavern spells and buffs
export const SPELLS = [
  // ── Keyword givers ──────────────────────────────────────────
  { id:"s1",  name:"Divine Shield",      icon:"🛡️",  color:"#60a5fa",
    effect: m => ({ ...m, divine_shield: true }),
    desc: "Give a minion Divine Shield." },
  { id:"s2",  name:"Taunt",             icon:"🗡️",  color:"#f59e0b",
    effect: m => ({ ...m, taunt: true }),
    desc: "Give a minion Taunt." },
  { id:"s3",  name:"Windfury",          icon:"💨",  color:"#a78bfa",
    effect: m => ({ ...m, windfury: true }),
    desc: "Give a minion Windfury." },
  { id:"s4",  name:"Poisonous",         icon:"☠️",  color:"#34d399",
    effect: m => ({ ...m, poisonous: true }),
    desc: "Give a minion Poisonous." },
  { id:"s5",  name:"Reborn",            icon:"🔄",  color:"#f87171",
    effect: m => ({ ...m, reborn: true }),
    desc: "Give a minion Reborn." },

  // ── Stat buffs ───────────────────────────────────────────────
  { id:"s6",  name:"+1/+1",            icon:"⚡",  color:"#fbbf24",
    effect: m => ({ ...m, currentAttack:(m.currentAttack??m.attack)+1, currentHealth:(m.currentHealth??m.health)+1 }),
    desc: "Give a minion +1/+1." },
  { id:"s7",  name:"+2/+2",            icon:"💥",  color:"#f97316",
    effect: m => ({ ...m, currentAttack:(m.currentAttack??m.attack)+2, currentHealth:(m.currentHealth??m.health)+2 }),
    desc: "Give a minion +2/+2." },
  { id:"s8",  name:"+3/+3",            icon:"🔥",  color:"#ef4444",
    effect: m => ({ ...m, currentAttack:(m.currentAttack??m.attack)+3, currentHealth:(m.currentHealth??m.health)+3 }),
    desc: "Give a minion +3/+3." },
  { id:"s9",  name:"+5 Attack",        icon:"⚔️",  color:"#ef4444",
    effect: m => ({ ...m, currentAttack:(m.currentAttack??m.attack)+5 }),
    desc: "Give a minion +5 Attack." },
  { id:"s10", name:"+5 Health",        icon:"💚",  color:"#34d399",
    effect: m => ({ ...m, currentHealth:(m.currentHealth??m.health)+5 }),
    desc: "Give a minion +5 Health." },
  { id:"s11", name:"Double Stats",     icon:"✨",  color:"#f4d03f",
    effect: m => ({ ...m,
      currentAttack:(m.currentAttack??m.attack)*2,
      currentHealth:(m.currentHealth??m.health)*2 }),
    desc: "Double a minion's stats." },

  // ── Board-wide buffs ─────────────────────────────────────────
  { id:"s12", name:"Battlecry: +1/+1 all", icon:"🌟", color:"#f4d03f",
    boardWide: true,
    effect: m => ({ ...m, currentAttack:(m.currentAttack??m.attack)+1, currentHealth:(m.currentHealth??m.health)+1 }),
    desc: "Give all your minions +1/+1." },
  { id:"s13", name:"Shields for all",  icon:"🛡️🛡️", color:"#60a5fa",
    boardWide: true,
    effect: m => ({ ...m, divine_shield: true }),
    desc: "Give all your minions Divine Shield." },

  // ── Removal ─────────────────────────────────────────────────
  { id:"s14", name:"Remove taunt",     icon:"🚫",  color:"#6b7280",
    effect: m => ({ ...m, taunt: false }),
    desc: "Remove Taunt from a minion." },
  { id:"s15", name:"Remove div.shield",icon:"💔",  color:"#6b7280",
    effect: m => ({ ...m, divine_shield: false }),
    desc: "Remove Divine Shield from a minion." },
];
